[package]
name = "frilday-desktop"
version = "0.1.0"
description = "FrilDay desktop client"
authors = ["FrilLab"]
license = ""
repository = "https://github.com/FrilLab/frilday"
edition = "2021"
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "frilday_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.4", features = [] }

[dependencies]
base64 = "0.22"
frilday-core = { path = "../../../crates/frilday-core" }
rand = "0.9"
reqwest = { version = "0.13.2", default-features = false, features = ["form", "json", "query", "rustls"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
sqlx = { version = "0.8", default-features = false, features = ["json", "runtime-tokio", "sqlite"] }
tokio = { version = "1", features = ["rt"] }
log = "0.4"
tauri = { version = "2.10.0", features = [] }
tauri-plugin-log = "2"
tauri-plugin-opener = "2.5.4"
tauri-plugin-store = "2.4.2"
tauri-plugin-sql = { version = "2.3.2", features = ["sqlite"] }
tauri-plugin-notification = "2.3.3"
url = "2.5"

[target.'cfg(target_os = "macos")'.dependencies]
keyring = { version = "3.6.3", default-features = false, features = ["apple-native"] }

[target.'cfg(target_os = "windows")'.dependencies]
keyring = { version = "3.6.3", default-features = false, features = ["windows-native"] }

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "3.6.3", default-features = false, features = ["linux-native-sync-persistent", "crypto-rust"] }

[target.'cfg(any(target_os = "freebsd", target_os = "openbsd"))'.dependencies]
keyring = { version = "3.6.3", default-features = false, features = ["sync-secret-service", "crypto-rust"] }
